name: Artifactlightning
version: ${project.version}
main: grouplightning.artifactlightning.Artifactlightning
api-version: 1.13
commands:
  ligline:
    description: Lightning boyz!
  ligstorm:
    description: More lightning!
  gaelwave:
    description: i'm just inventing shit now
  lightningstrike:
    description: lightning stuff